#!/usr/bin/env python3
"""Fails when the declared protobuf floor is below what the bindings demand.

protoc stamps every generated module with the version that produced it, and
the runtime refuses to load gencode newer than itself:

    VersionError: gencode 7.35.1 runtime 6.33.1.
    Runtime version cannot be older than the linked gencode version.

The bindings here are generated by the protoc the CMake build produces, so
their stamp moves whenever the vendored protobuf moves -- while the floor in
pyproject.toml sits still. v8.1.1 shipped with gencode 7.35.1 and a declared
`protobuf>=4.25`, so every install that resolved protobuf 4, 5 or 6 satisfied
pip and then died on import. Nothing caught it because the CI job installed
the newest protobuf, which is the one case that works.

Run after generating the bindings and before building the wheel:

    tools/scripts/check_protobuf_floor.py --pb python/bindiff/_pb \
        --pyproject python/pyproject.toml
"""

from __future__ import annotations

import argparse
import ast
import sys
import tomllib
from pathlib import Path
from typing import List, Optional, Tuple

Version = Tuple[int, int, int]


class Mismatch(Exception):
    """The declaration and the generated code disagree."""


def gencode_version(source: str) -> Optional[Version]:
    """The (major, minor, patch) protoc stamped into one _pb2 module.

    Read from the syntax tree rather than by regex: the call is generated
    code whose formatting is protoc's business, and a pattern that matched
    today's layout would silently match nothing after a protoc release --
    reporting "no version found", which this treats as a reason to fail
    rather than a reason to pass.
    """
    tree = ast.parse(source)
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        name = func.attr if isinstance(func, ast.Attribute) else getattr(
            func, "id", None)
        if name != "ValidateProtobufRuntimeVersion":
            continue
        numbers = [a.value for a in node.args
                   if isinstance(a, ast.Constant) and isinstance(a.value, int)]
        if len(numbers) >= 3:
            return (numbers[0], numbers[1], numbers[2])
    return None


def declared_floor(pyproject: str) -> Optional[Version]:
    """The >= bound on protobuf in [project.dependencies].

    Only >= is considered a floor. A bare `protobuf` or a `!=` exclusion
    places no lower bound at all, which is the same failure as too low a one
    and is reported the same way.
    """
    from packaging.requirements import Requirement

    data = tomllib.loads(pyproject)
    for entry in data.get("project", {}).get("dependencies", []):
        requirement = Requirement(entry)
        if requirement.name.lower().replace("_", "-") != "protobuf":
            continue
        for spec in requirement.specifier:
            if spec.operator in (">=", "=="):
                parts = [int(p) for p in spec.version.split(".")[:3]]
                while len(parts) < 3:
                    parts.append(0)
                return tuple(parts)  # type: ignore[return-value]
    return None


def check(modules: List[Tuple[str, str]], pyproject: str) -> Version:
    """Returns the highest gencode version found. Raises Mismatch otherwise."""
    stamps = []
    for name, source in modules:
        version = gencode_version(source)
        if version is None:
            raise Mismatch(
                f"{name} carries no ValidateProtobufRuntimeVersion call; "
                "either protoc stopped emitting one or this stopped being "
                "generated code, and neither should pass silently")
        stamps.append((version, name))
    if not stamps:
        raise Mismatch("no generated modules were given to check")

    highest, source_name = max(stamps)
    floor = declared_floor(pyproject)
    if floor is None:
        raise Mismatch(
            "no >= floor on protobuf in [project.dependencies]; the bindings "
            f"need at least {'.'.join(map(str, highest))}")
    if floor < highest:
        raise Mismatch(
            f"{source_name} was generated by protoc "
            f"{'.'.join(map(str, highest))} and the runtime refuses gencode "
            f"newer than itself, but pyproject.toml declares protobuf>="
            f"{'.'.join(map(str, floor))}. An install that resolves a "
            "protobuf between the two satisfies pip and then fails on "
            f"import. Raise the floor to >={'.'.join(map(str, highest))}.")
    return highest


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pb", required=True,
                        help="directory holding the generated *_pb2.py")
    parser.add_argument("--pyproject", required=True)
    args = parser.parse_args(argv)

    generated = sorted(Path(args.pb).glob("*_pb2.py"))
    if not generated:
        print(f"error: no *_pb2.py under {args.pb}", file=sys.stderr)
        return 1

    try:
        highest = check([(p.name, p.read_text(encoding="utf-8"))
                         for p in generated],
                        Path(args.pyproject).read_text(encoding="utf-8"))
    except Mismatch as exc:
        print(f"::error::{exc}", file=sys.stderr)
        return 1

    print(f"protobuf floor covers gencode {'.'.join(map(str, highest))} "
          f"across {len(generated)} generated modules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
