"""Tests for the protobuf floor check.

v8.1.1 shipped bindings generated by protoc 7.35.1 behind a declared
`protobuf>=4.25`. The runtime refuses gencode newer than itself, so every
install that resolved protobuf 4, 5 or 6 satisfied pip and then raised
VersionError on the first import. The wheel job never saw it because it
installs the newest protobuf, which is the one case that works.

These tests drive the checker with synthetic inputs rather than the generated
tree, which does not exist in a fresh checkout.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

_MODULE = (Path(__file__).resolve().parents[2] / "tools" / "scripts"
           / "check_protobuf_floor.py")
_spec = importlib.util.spec_from_file_location("check_protobuf_floor", _MODULE)
check_protobuf_floor = importlib.util.module_from_spec(_spec)
sys.modules["check_protobuf_floor"] = check_protobuf_floor
_spec.loader.exec_module(check_protobuf_floor)

Mismatch = check_protobuf_floor.Mismatch
check = check_protobuf_floor.check
declared_floor = check_protobuf_floor.declared_floor
gencode_version = check_protobuf_floor.gencode_version


def generated(major, minor, patch, name="binexport2.proto"):
    """What protoc emits at the top of a _pb2 module."""
    return (
        "from google.protobuf import runtime_version as _runtime_version\n"
        "_runtime_version.ValidateProtobufRuntimeVersion(\n"
        "    _runtime_version.Domain.PUBLIC,\n"
        f"    {major},\n    {minor},\n    {patch},\n"
        f"    '',\n    '{name}'\n)\n")


def pyproject(dependency):
    return ('[project]\nname = "bindiff-ng"\nversion = "8.1.2"\n'
            f'dependencies = [\n    "{dependency}",\n]\n')


class TestReadingTheStamp:
    def test_reads_the_version_protoc_wrote(self):
        assert gencode_version(generated(7, 35, 1)) == (7, 35, 1)

    def test_survives_reformatting(self):
        """Parsed from the syntax tree, not matched as text: the layout is
        protoc's business and changes between releases."""
        one_line = ("_runtime_version.ValidateProtobufRuntimeVersion("
                    "_runtime_version.Domain.PUBLIC, 7, 35, 1, '', 'x.proto')")
        assert gencode_version(one_line) == (7, 35, 1)

    def test_a_module_without_the_call_reads_as_none(self):
        assert gencode_version("X = 1\n") is None


class TestTheFloor:
    def test_reads_a_ge_bound(self):
        assert declared_floor(pyproject("protobuf>=7.35.1")) == (7, 35, 1)

    def test_pads_a_short_version(self):
        assert declared_floor(pyproject("protobuf>=4.25")) == (4, 25, 0)

    def test_ignores_other_dependencies(self):
        source = ('[project]\nname = "x"\nversion = "1"\n'
                  'dependencies = ["rich>=13", "protobuf>=7.35.1"]\n')
        assert declared_floor(source) == (7, 35, 1)

    def test_an_unbounded_dependency_is_no_floor(self):
        """`protobuf` alone permits any version, which fails exactly the way
        too low a floor does."""
        assert declared_floor(pyproject("protobuf")) is None


class TestCheck:
    def test_the_bug_that_shipped_is_caught(self):
        with pytest.raises(Mismatch, match=r"7\.35\.1"):
            check([("binexport2_pb2.py", generated(7, 35, 1))],
                  pyproject("protobuf>=4.25"))

    def test_an_adequate_floor_passes(self):
        assert check([("binexport2_pb2.py", generated(7, 35, 1))],
                     pyproject("protobuf>=7.35.1")) == (7, 35, 1)

    def test_a_higher_floor_than_needed_passes(self):
        """Stricter than necessary is a choice, not a defect."""
        assert check([("a_pb2.py", generated(7, 35, 1))],
                     pyproject("protobuf>=7.36.0")) == (7, 35, 1)

    def test_the_highest_stamp_across_modules_governs(self):
        """Two protos generated by different protocs is a broken build, but
        the floor must still cover the newer of them rather than whichever
        module happened to sort first."""
        with pytest.raises(Mismatch, match=r"8\.0\.0"):
            check([("a_pb2.py", generated(7, 35, 1)),
                   ("b_pb2.py", generated(8, 0, 0))],
                  pyproject("protobuf>=7.35.1"))

    def test_a_missing_stamp_fails_rather_than_passes(self):
        """Silence is the failure mode this exists to prevent, so a module
        with no call is an error, not a module that needs nothing."""
        with pytest.raises(Mismatch, match="no ValidateProtobufRuntimeVersion"):
            check([("binexport2_pb2.py", "X = 1\n")],
                  pyproject("protobuf>=7.35.1"))

    def test_an_unbounded_dependency_fails(self):
        with pytest.raises(Mismatch, match="no >= floor"):
            check([("a_pb2.py", generated(7, 35, 1))], pyproject("protobuf"))
